<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>alias</string>
		<string>snippet</string>
		<string>gvar</string>
	</array>
	<key>firstLineMatch</key>
	<string></string>
	<key>foldingStartMarker</key>
	<string></string>
	<key>foldingStopMarker</key>
	<string></string>
	<key>name</key>
	<string>Draconic</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\B\-[title|desc|image|footer|f|phrase|sb|attack|i|h|here|d|b|thumb|color|adv|dis|sadv|sdis]+[0-9]*\b</string>
			<key>name</key>
			<string>markup.raw</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.block punctuation.section.block.begin entity.name.tag</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.block punctuation.section.block.begin entity.name.tag</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;drac2&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.definition.code-fence.begin meta.tag entity.name.tag</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&lt;/drac2&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.code-fence.definition.end meta.tag entity.name.tag</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\A{</string>
			<key>end</key>
			<string>}\Z</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.json</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\A\[</string>
			<key>end</key>
			<string>\]\z</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.json</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(&lt;)[^&lt;&gt;]+(&gt;)</string>
			<key>name</key>
			<string>entity.name.constant</string>
		</dict>
		<dict>
			<key>match</key>
			<string>({)[^{}]+(})</string>
			<key>name</key>
			<string>entity.name.constant</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(%([0-9]+|*)%|&amp;([0-9]+|ARGS|*)&amp;)</string>
			<key>name</key>
			<string>markup.inserted</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.draconic</string>
</dict>
</plist>
